### ISSUE TITLE
Supported versions in version negotiation packet

### ISSUE THREAD

**Issue by xiaojian-hong** [goburrow/quic#1]
Currently, quiwi uses the latest supported version (draft-32) during version negotiation.
https://github.com/goburrow/quic/blob/c6121e3eccc2ea7aed57ed4ab064974cc730c5be/transport/packet.go#L479

When I use quiwi as server, and quiche as client (supported draft-27 to draft-29), I got the `unsupported version` error because quiwi returns the version draft-32 which doesn't support in quiche.
As I understand, quiwi supports the versions between the minimum version draft-29 to draft-32? If so, I will create a PR to add all versions draft-29 ... draft-32 to [`supportedVersions` slice](
https://github.com/goburrow/quic/blob/c6121e3eccc2ea7aed57ed4ab064974cc730c5be/transport/packet.go#L479)? Then quiwi and quiche will use draft-29. :)

Or quiwi doesn't support the backward compatible with draft-29 to draft-31 after upgraded to draft-32?

**Comment by nqv** [comment]
You're right, version in the version negotiation is always the latest atm. If quiche sent version draft-29, it would be supported by quiwi and version negotiation will not be performed. I'll try to fix it.

**Comment by nqv** [comment]
I have updated and checked quiche client can negotiate version now. Would you please confirm?

**Comment by xiaojian-hong** [comment]
> I have updated and checked quiche client can negotiate version now. Would you please confirm?

Great! It works now, thanks.

**Comment by nqv** [comment]
Thank you, I've tagged a new version v0.0.5
